#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyUALife.Resource", IsApplication=true)]

namespace MyUALife
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int grey300 = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int grey500 = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int grey800 = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int invis = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int switch_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int switch_border = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060015
			public const int addEventButton = 2131099669;
			
			// aapt resource value: 0x7f060003
			public const int backButton = 2131099651;
			
			// aapt resource value: 0x7f060018
			public const int calendarButton = 2131099672;
			
			// aapt resource value: 0x7f060011
			public const int changeEndButton = 2131099665;
			
			// aapt resource value: 0x7f06000c
			public const int changeStartButton = 2131099660;
			
			// aapt resource value: 0x7f060020
			public const int createDeadlineButton = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int createEventButton = 2131099679;
			
			// aapt resource value: 0x7f060000
			public const int dayLabel = 2131099648;
			
			// aapt resource value: 0x7f06001b
			public const int deadlinesRadioButton = 2131099675;
			
			// aapt resource value: 0x7f060007
			public const int descriptionText = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int endTimeLabel = 2131099663;
			
			// aapt resource value: 0x7f060001
			public const int eventsLayout = 2131099649;
			
			// aapt resource value: 0x7f060019
			public const int eventsRadioButton = 2131099673;
			
			// aapt resource value: 0x7f060016
			public const int externalCalendarButton = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int filterButton = 2131099671;
			
			// aapt resource value: 0x7f06001e
			public const int happeningsButton = 2131099678;
			
			// aapt resource value: 0x7f06000e
			public const int linearLayout1 = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int linearLayout2 = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout3 = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout4 = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int mainCalendar = 2131099667;
			
			// aapt resource value: 0x7f06001d
			public const int mainTextLayout = 2131099677;
			
			// aapt resource value: 0x7f060005
			public const int nameText = 2131099653;
			
			// aapt resource value: 0x7f060014
			public const int openDayViewButton = 2131099668;
			
			// aapt resource value: 0x7f060002
			public const int optionsText = 2131099650;
			
			// aapt resource value: 0x7f06001a
			public const int radioGroup1 = 2131099674;
			
			// aapt resource value: 0x7f060012
			public const int saveEditButton = 2131099666;
			
			// aapt resource value: 0x7f06001c
			public const int scrollView1 = 2131099676;
			
			// aapt resource value: 0x7f06000a
			public const int startTimeLabel = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int textView1 = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int textView2 = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int textView3 = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int textView4 = 2131099661;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DayView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EventView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NewMain = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
